import time
print(" > snoew cleaner v1.0")
time.sleep(0.25)
open('encryptions.txt', 'w').close()
print(">> 1/2 clear")
time.sleep(0.25)
open('decryptions.txt', 'w').close()
print(">> 2/2 clear")
time.sleep(0.25)
print(">> All logs have been cleared")
time.sleep(0.25)
print("Closing...")
time.sleep(1)
